server:
  port: 8081
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    session:
      timeout: 30m

spring:
  datasource:
    url: ${data.url}
    username: ${data.username}
    password: ${data.password}
    driver-class-name: org.postgresql.Driver
  config:
    import: classpath:jwt.yml, classpath:database.yml
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_schema: ${data.schema}
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  jwt:
    secret: ${jwt.secret}

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace
