server:
  port: 8081
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    session:
      timeout: 30m

spring:
  datasource:
    url: ${data.url}
    username: ${data.username}
    password: ${data.password}
    driver-class-name: org.postgresql.Driver
  config:
    import: classpath:jwt.yml, classpath:database.yml, classpath:google-oauth2.yml, classpath:aws-s3.yml
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_schema: ${data.schema}
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  jwt:
    secret: ${jwt.secret}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${google.id}
            client-secret: ${google.password}
            scope:
              - profile
              - email
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1GB

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace
      springframework:
        security: debug
    root: info

#google:
#  cloud:
#    translation:
#      credentials:
#        file:
#          path: ${google.translation.json-key}

aws:
  cloud:
    s3:
      bucket: ${s3.bucket-name}
    region:
      static: ${s3.region}
      auto: false
    stack:
      auto: false
    credentials:
      access-key: ${s3.access-key}
      secret-key: ${s3.secret-key}